[2024-03-04T00:21:45.069+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:21:45.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:21:45.074+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:21:45.072+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:21:45.132+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:21:45.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:21:45.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:21:45.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T00:22:15.274+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:15.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:22:15.276+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:22:15.276+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:15.330+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:22:15.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:22:15.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:15.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:22:45.436+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:45.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:22:45.438+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:22:45.438+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:45.496+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:22:45.495+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:22:45.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:22:45.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.096 seconds
[2024-03-04T00:23:15.609+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:15.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:23:15.611+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:23:15.611+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:15.666+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:23:15.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:23:15.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:15.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:23:45.780+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:45.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:23:45.782+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:23:45.782+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:45.844+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:23:45.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:23:45.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:23:45.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:24:15.946+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:15.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:24:15.948+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:24:15.948+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:16.004+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:24:16.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:24:16.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:16.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:24:46.126+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:46.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:24:46.129+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:24:46.128+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:46.187+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:24:46.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:24:46.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:24:46.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:25:16.289+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:16.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:25:16.292+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:25:16.292+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:16.352+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:25:16.351+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:25:16.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:16.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.093 seconds
[2024-03-04T00:25:46.466+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:46.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:25:46.468+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:25:46.468+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:46.528+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:25:46.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:25:46.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:25:46.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:26:16.628+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:16.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:26:16.631+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:26:16.631+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:16.686+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:26:16.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:26:16.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:16.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:26:46.817+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:46.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:26:46.820+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:26:46.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:46.880+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:26:46.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:26:46.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:26:46.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.097 seconds
[2024-03-04T00:29:21.253+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:21.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:29:21.256+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:29:21.256+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:21.312+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:29:21.311+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:29:21.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:21.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.087 seconds
[2024-03-04T00:29:51.455+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:51.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:29:51.457+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:29:51.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:51.510+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:29:51.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:29:51.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:29:51.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.089 seconds
[2024-03-04T00:30:21.615+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:21.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:30:21.618+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:30:21.617+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:21.685+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:30:21.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:30:21.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:21.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.100 seconds
[2024-03-04T00:30:51.807+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:51.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:30:51.810+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:30:51.809+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:51.870+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:30:51.869+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:30:51.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:30:51.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.100 seconds
[2024-03-04T00:31:21.975+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:21.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:31:21.979+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:31:21.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:22.043+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:31:22.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:31:22.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:22.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.104 seconds
[2024-03-04T00:31:52.145+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:52.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:31:52.147+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:31:52.147+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:52.204+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:31:52.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:31:52.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:31:52.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T00:32:22.319+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:22.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:32:22.322+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:32:22.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:22.378+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:32:22.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:32:22.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:22.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T00:32:52.502+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:52.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:32:52.504+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:32:52.504+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:52.566+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:32:52.565+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:32:52.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:32:52.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.103 seconds
[2024-03-04T00:33:22.681+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:22.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:33:22.684+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:33:22.683+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:22.746+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:33:22.744+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:33:22.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:22.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.102 seconds
[2024-03-04T00:33:52.852+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:52.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:33:52.855+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:33:52.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:52.912+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:33:52.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:33:52.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:33:52.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:34:23.045+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:23.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:34:23.047+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:34:23.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:23.109+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:34:23.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:34:23.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:23.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.100 seconds
[2024-03-04T00:34:53.205+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:53.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:34:53.207+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:34:53.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:53.272+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:34:53.271+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:34:53.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:34:53.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T00:35:23.402+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:23.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:35:23.405+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:35:23.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:23.465+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:35:23.464+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:35:23.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:23.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.097 seconds
[2024-03-04T00:35:53.556+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:53.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:35:53.558+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:35:53.558+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:53.613+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:35:53.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:35:53.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:35:53.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:36:23.762+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:23.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:36:23.765+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:36:23.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:23.817+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:36:23.816+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:36:23.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:23.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.090 seconds
[2024-03-04T00:36:53.930+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:53.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:36:53.932+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:36:53.932+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:53.991+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:36:53.990+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:36:53.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:36:54.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T00:37:24.119+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:24.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:37:24.122+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:37:24.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:24.184+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:37:24.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:37:24.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:24.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.102 seconds
[2024-03-04T00:37:54.282+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:54.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:37:54.285+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:37:54.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:54.341+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:37:54.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:37:54.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:37:54.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:38:24.479+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:24.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:38:24.481+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:38:24.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:24.533+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:38:24.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:38:24.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:24.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:38:54.647+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:54.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:38:54.651+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:38:54.650+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:54.712+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:38:54.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:38:54.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:38:54.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.098 seconds
[2024-03-04T00:39:24.836+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:24.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:39:24.841+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:39:24.840+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:24.894+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:39:24.893+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:39:24.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:24.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.093 seconds
[2024-03-04T00:39:54.999+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:55.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:39:55.002+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:39:55.001+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:55.047+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:39:55.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:39:55.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:39:55.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.076 seconds
[2024-03-04T00:40:25.191+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:25.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:40:25.195+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:40:25.194+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:25.257+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:40:25.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:40:25.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:25.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.098 seconds
[2024-03-04T00:40:55.348+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:55.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:40:55.351+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:40:55.351+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:55.413+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:40:55.412+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:40:55.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:40:55.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:41:25.553+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:25.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:41:25.556+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:41:25.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:25.612+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:41:25.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:41:25.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:25.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T00:41:55.710+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:55.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:41:55.713+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:41:55.712+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:55.768+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:41:55.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:41:55.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:41:55.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.087 seconds
[2024-03-04T00:42:25.901+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:25.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:42:25.904+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:42:25.904+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:25.960+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:42:25.959+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:42:25.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:25.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:42:56.066+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:56.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:42:56.069+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:42:56.068+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:56.132+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:42:56.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:42:56.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:42:56.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.098 seconds
[2024-03-04T00:43:26.236+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:26.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:43:26.239+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:43:26.238+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:26.295+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:43:26.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:43:26.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:26.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:43:56.413+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:56.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:43:56.417+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:43:56.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:56.476+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:43:56.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:43:56.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:43:56.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T00:44:26.590+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:26.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:44:26.593+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:44:26.592+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:26.653+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:44:26.652+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:44:26.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:26.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:44:56.772+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:56.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:44:56.775+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:44:56.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:56.828+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:44:56.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:44:56.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:44:56.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:45:26.938+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:26.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:45:26.940+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:45:26.940+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:27.003+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:45:27.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:45:27.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:27.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.100 seconds
[2024-03-04T00:45:57.122+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:57.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:45:57.126+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:45:57.126+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:57.207+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:45:57.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:45:57.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:45:57.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.120 seconds
[2024-03-04T00:46:27.302+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:27.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:46:27.305+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:46:27.305+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:27.369+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:46:27.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:46:27.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:27.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.096 seconds
[2024-03-04T00:46:57.482+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:57.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:46:57.486+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:46:57.485+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:57.541+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:46:57.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:46:57.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:46:57.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T00:47:27.652+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:27.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:47:27.655+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:47:27.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:27.710+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:47:27.709+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:47:27.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:27.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.087 seconds
[2024-03-04T00:47:57.834+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:57.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:47:57.837+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:47:57.836+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:57.891+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:47:57.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:47:57.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:47:57.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.093 seconds
[2024-03-04T00:48:28.001+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:28.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:48:28.004+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:48:28.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:28.067+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:48:28.066+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:48:28.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:28.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.098 seconds
[2024-03-04T00:48:58.168+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:58.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:48:58.170+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:48:58.170+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:58.228+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:48:58.227+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:48:58.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:48:58.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:51:43.832+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:51:43.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:51:43.835+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:51:43.834+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:51:43.892+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:51:43.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:51:43.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:51:43.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T00:52:14.026+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:14.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:52:14.029+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:52:14.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:14.082+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:52:14.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:52:14.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:14.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.086 seconds
[2024-03-04T00:52:44.184+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:44.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:52:44.186+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:52:44.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:44.244+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:52:44.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:52:44.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:52:44.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.105 seconds
[2024-03-04T00:53:14.355+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:14.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:53:14.358+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:53:14.357+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:14.400+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:53:14.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:53:14.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:14.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.073 seconds
[2024-03-04T00:53:44.534+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:44.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:53:44.537+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:53:44.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:44.595+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:53:44.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:53:44.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:53:44.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.093 seconds
[2024-03-04T00:54:14.693+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:14.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:54:14.696+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:54:14.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:14.757+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:54:14.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:54:14.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:14.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T00:54:44.870+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:44.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:54:44.874+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:54:44.873+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:44.931+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:54:44.930+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:54:44.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:54:44.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.095 seconds
[2024-03-04T00:55:15.026+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:55:15.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:55:15.029+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:55:15.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:55:15.083+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:55:15.082+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:55:15.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:55:15.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T00:58:17.702+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:17.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:58:17.707+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:58:17.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:17.770+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:58:17.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:58:17.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:17.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.100 seconds
[2024-03-04T00:58:47.914+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:47.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:58:47.917+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:58:47.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:48.016+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:58:48.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:58:48.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:58:48.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.145 seconds
[2024-03-04T00:59:18.107+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:18.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:59:18.110+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:59:18.109+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:18.168+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:59:18.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:59:18.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:18.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T00:59:48.327+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:48.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T00:59:48.330+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:59:48.329+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:48.383+0000] {logging_mixin.py:188} INFO - [2024-03-04T00:59:48.382+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T00:59:48.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T00:59:48.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.090 seconds
[2024-03-04T01:00:18.478+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:18.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:00:18.480+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:00:18.480+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:18.541+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:00:18.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:00:18.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:18.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.091 seconds
[2024-03-04T01:00:48.669+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:48.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:00:48.672+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:00:48.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:48.716+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:00:48.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:00:48.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:00:48.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.077 seconds
[2024-03-04T01:01:18.821+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:18.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:01:18.823+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:01:18.823+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:18.885+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:01:18.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:01:18.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:18.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.098 seconds
[2024-03-04T01:01:49.014+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:49.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:01:49.016+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:01:49.016+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:49.075+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:01:49.074+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:01:49.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:01:49.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.095 seconds
[2024-03-04T01:02:19.184+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:19.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:02:19.187+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:02:19.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:19.240+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:02:19.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:02:19.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:19.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.086 seconds
[2024-03-04T01:02:49.379+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:49.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:02:49.383+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:02:49.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:49.441+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:02:49.440+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:02:49.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:02:49.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T01:03:19.545+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:19.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:03:19.548+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:03:19.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:19.606+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:03:19.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:03:19.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:19.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.094 seconds
[2024-03-04T01:03:49.738+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:49.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:03:49.741+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:03:49.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:49.802+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:03:49.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:03:49.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:03:49.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.099 seconds
[2024-03-04T01:04:19.889+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:19.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:04:19.891+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:04:19.891+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:19.935+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:04:19.934+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:04:19.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:19.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.077 seconds
[2024-03-04T01:04:50.102+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:50.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:04:50.105+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:04:50.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:50.157+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:04:50.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:04:50.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:04:50.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.090 seconds
[2024-03-04T01:05:20.258+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:20.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:05:20.261+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:05:20.260+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:20.317+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:05:20.316+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:05:20.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:20.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T01:05:50.446+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:50.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:05:50.448+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:05:50.448+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:50.497+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:05:50.496+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:05:50.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:05:50.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.080 seconds
[2024-03-04T01:06:20.625+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:20.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:06:20.628+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:06:20.627+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:20.684+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:06:20.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:06:20.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:20.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.095 seconds
[2024-03-04T01:06:50.786+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:50.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:06:50.788+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:06:50.787+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:50.842+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:06:50.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:06:50.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:06:50.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.086 seconds
[2024-03-04T01:07:20.977+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:20.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:07:20.981+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:07:20.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:21.052+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:07:21.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:07:21.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:21.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.115 seconds
[2024-03-04T01:07:51.138+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:51.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:07:51.141+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:07:51.141+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:51.195+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:07:51.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:07:51.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:07:51.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.088 seconds
[2024-03-04T01:08:21.368+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:21.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:08:21.371+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:08:21.370+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:21.425+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:08:21.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:08:21.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:21.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.097 seconds
[2024-03-04T01:08:51.525+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:51.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:08:51.528+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:08:51.528+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:51.588+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:08:51.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:08:51.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:08:51.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.095 seconds
[2024-03-04T01:09:21.727+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:21.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:09:21.730+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:09:21.730+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:21.784+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:09:21.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:09:21.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:21.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.092 seconds
[2024-03-04T01:09:51.882+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:51.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka_stream_metrics.py for tasks to queue
[2024-03-04T01:09:51.885+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:09:51.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:51.948+0000] {logging_mixin.py:188} INFO - [2024-03-04T01:09:51.947+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/kafka_stream_metrics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka_stream_metrics.py", line 4, in <module>
    from kafka import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-03-04T01:09:51.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka_stream_metrics.py
[2024-03-04T01:09:51.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka_stream_metrics.py took 0.102 seconds
